---
title: "FINAL"
format: html
editor: visual
---

## Merge Data

```{r}
library(dplyr)
data2 <- read.csv("previous_years.csv")

data1 <- read.csv("edheat2025_live.csv")

d <- bind_rows(data2, data1)
#Combines data sets with similar rows and columns

d$date <- as.Date(d$END_DATE)
d$END_DATE <- NULL
#Date conversion
d$yr <- as.integer(format(d$date, "%Y"))

d$Month <- as.integer(format(d$date, "%m"))
#Month Variable

```

## Year

```{r}
# Create daily dates for June, 2019-2023 - CHANGE (2017-2025)
date <- seq(as.Date("2017-05-01"), as.Date("2025-09-30"), by = "day")
date <- date[format(date, "%m") %in% c("05","06","07","08","09")]


#Deleted Simulated Temp & Data Frame 

# Split temperatures by year so lags reset each May-September
d$yr <- format(d$date, "%Y")
temp_by_year <- split(d$MAX_DAILY_TEMP, yr)



#Quasi-Poisson regression
quasi_pois_model_yr <- glm(
  HEAT_ED_VISIT_COUNT ~ MAX_DAILY_TEMP+yr,
  family = quasipoisson(link = "log"),
  data = d
)
summary(quasi_pois_model_yr)


quasi_pois_model_yrf <- glm(
  HEAT_ED_VISIT_COUNT ~ MAX_DAILY_TEMP+as.factor(yr),
  family = quasipoisson(link = "log"),
  data = d
)
summary(quasi_pois_model_yrf)

summary(quasi_pois_model)

#Graphing 
plot(
  d$MAX_DAILY_TEMP,
  d$HEAT_ED_VISIT_COUNT,
  pch = 16,
  col = "black",
  xlab = "Maximum Daily Temperature",
  ylab = "Heat ED Visit Count",
  main = "Quasi-Poisson Regression"
)

#Line
lines(
  sort(d$MAX_DAILY_TEMP),
  fitted(quasi_pois_model)[order(d$MAX_DAILY_TEMP)],
  col = "red",
  lwd = 2
)




# Create lag0 through lag6 within each year
for (i in 0:6) {
  d[[paste0("lag", i)]] <- unlist(
    lapply(temp_by_year, function(x) {
      if (i == 0) {
        x
      } else {
        c(rep(NA, i), head(x, -i))
      }
    }),
    use.names = FALSE
  )
}

head(d[, c("date", "MAX_DAILY_TEMP",
           "lag1",
           "lag6")])

```

## Month

```{r}
d$Month <- format(d$date, "%m")
temp_by_month <- split(d$MAX_DAILY_TEMP, d$Month)


quasi_pois_model_mf <- glm(
  HEAT_ED_VISIT_COUNT ~ MAX_DAILY_TEMP+as.factor(Month),
  family = quasipoisson(link = "log"),
  data = d
)
summary(quasi_pois_model_mf)

#summary(quasi_pois_model)

#Graphing 
plot(
  d$MAX_DAILY_TEMP,
  d$HEAT_ED_VISIT_COUNT,
  pch = 16,
  col = "black",
  xlab = "Maximum Daily Temperature",
  ylab = "Heat ED Visit Count",
  main = "Quasi-Poisson Regression"
)

#Line
lines(
  sort(d$MAX_DAILY_TEMP),
  fitted(quasi_pois_model)[order(d$MAX_DAILY_TEMP)],
  col = "red",
  lwd = 2
)

```

## Holiday

```{r}

# Independence Day
d$july4 <- ifelse(format(d$date, "%m-%d") == "07-04",1,0)

# Juneteenth
d$juneteenth <- ifelse(format(d$date, "%m-%d") == "06-19",1,0)

# Mother's Day
mother <- as.Date(sapply(d$yr, function(y) {
  x <- as.Date(paste0(y, "-05-01"))
  x + (8 - as.POSIXlt(x)$wday) %% 7 + 6
}))
d$mother <- ifelse(d$date == mother,1,0)

# Father's Day
father <- as.Date(sapply(d$yr, function(y) {
  x <- as.Date(paste0(y, "-06-01"))
  x + (8 - as.POSIXlt(x)$wday) %% 7 + 13
}))
d$father <- ifelse(d$date == father,1,0)

# Memorial Day
memorial <- as.Date(sapply(d$yr, function(y) {
  x <- as.Date(paste0(y, "-05-01"))
  x - as.POSIXlt(x)$wday %% 7 + 29
}))
d$memorial <- ifelse(d$date == memorial,1,0)

# Labor Day
labor <- as.Date(sapply(d$yr, function(y) {
  x <- as.Date(paste0(y, "-09-01"))
  x + (8 - as.POSIXlt(x)$wday) %% 7
}))
d$labor <- ifelse(d$date == labor,1,0)

# single holiday
d$holiday <- as.integer(d$july4 | d$memorial | d$labor | d$juneteenth | d$mother | d$father)
```

## All Covariates + Lag 0

```{r}
install.packages('car')
library(car)
# vif(quasi_pois_model_all)
quasi_pois_model_all <- glm(
  HEAT_ED_VISIT_COUNT ~ MAX_DAILY_TEMP+as.factor(d$Month)+d$holiday+as.factor(yr),
  family = quasipoisson(link = "log"),
  data = d
)
summary(quasi_pois_model_all)

#Graphing 
plot(
  d$MAX_DAILY_TEMP,
  d$HEAT_ED_VISIT_COUNT,
  pch = 16,
  col = "black",
  xlab = "Maximum Daily Temperature",
  ylab = "Heat ED Visit Count",
  main = "Quasi-Poisson Regression with Covariates"
)

#Line
lines(
  sort(d$MAX_DAILY_TEMP),
  fitted(quasi_pois_model_all)[order(d$MAX_DAILY_TEMP)],
  col = "red",
  lwd = 2
)
 

```

## Confidence interval

```{r}
ci_log <- confint.default(quasi_pois_model_all)
print(ci_log)

ci_irr <- ((exp(ci_log))*100)
print(ci_irr)
```

| Coefficient    | Estimate | Pr(\|t\|) | 95% CI         |
|----------------|----------|-----------|----------------|
| MAX_DAILY_TEMP | 15.7%    | \<2e-16   | (15.0%, 16.4%) |

```{r}
d3 <- read.csv("edheat2026_live.csv")

#Date, Month, And Year Variable

d3$date <- as.Date(d3$END_DATE)
d3$END_DATE <- NULL

d3$yr <- as.numeric(format(d3$date, "%Y"))

d3$Month <- as.numeric(format(d3$date, "%m"))

#Holiday

# Independence Day
d3$july4 <- ifelse(format(d3$date, "%m-%d") == "07-04",1,0)

# Juneteenth
d3$juneteenth <- ifelse(format(d3$date, "%m-%d") == "06-19",1,0)

# Mother's Day
mother <- as.Date(sapply(d3$yr, function(y) {
  x <- as.Date(paste0(y, "-05-01"))
  x + (8 - as.POSIXlt(x)$wday) %% 7 + 6
}))
d3$mother <- ifelse(d3$date == mother,1,0)

# Father's Day
father <- as.Date(sapply(d3$yr, function(y) {
  x <- as.Date(paste0(y, "-06-01"))
  x + (8 - as.POSIXlt(x)$wday) %% 7 + 13
}))
d3$father <- ifelse(d3$date == father,1,0)

# Memorial Day
memorial <- as.Date(sapply(d3$yr, function(y) {
  x <- as.Date(paste0(y, "-05-01"))
  x - as.POSIXlt(x)$wday %% 7 + 29
}))
d3$memorial <- ifelse(d3$date == memorial,1,0)

# Labor Day
labor <- as.Date(sapply(d3$yr, function(y) {
  x <- as.Date(paste0(y, "-09-01"))
  x + (8 - as.POSIXlt(x)$wday) %% 7
}))
d3$labor <- ifelse(d3$date == labor,1,0)

# single holiday
d3$holiday <- as.integer(d3$july4 | d3$memorial | d3$labor | d3$juneteenth | d3$mother | d3$father)

```

```         
```

## All Covariates + Lag 1

```{r}
quasi_pois_model_lag1 <- glm(
  HEAT_ED_VISIT_COUNT ~ lag1+as.factor(Month)+holiday+as.factor(yr),
  family = quasipoisson(link = "log"),
  data = d
)
summary(quasi_pois_model_lag1)
```

## All Covariates + Lag 2

```{r}
quasi_pois_model_lag2 <- glm(
  HEAT_ED_VISIT_COUNT ~ lag2+as.factor(Month)+holiday+as.factor(yr),
  family = quasipoisson(link = "log"),
  data = d
)
summary(quasi_pois_model_lag2)
```

## All Covariates + Lag 3

```{r}
quasi_pois_model_lag3 <- glm(
  HEAT_ED_VISIT_COUNT ~ lag3+as.factor(Month)+holiday+as.factor(yr),
  family = quasipoisson(link = "log"),
  data = d
)
summary(quasi_pois_model_lag3)
```

## All Covariates + Lag 4

```{r}
quasi_pois_model_lag4 <- glm(
  HEAT_ED_VISIT_COUNT ~ lag4+as.factor(Month)+holiday+as.factor(yr),
  family = quasipoisson(link = "log"),
  data = d
)
summary(quasi_pois_model_lag4)
```

D3 Data

```{r}
d3 <- read.csv("edheat2026_live.csv")

#Date, Month, And Year Variable

d3$date <- as.Date(d3$END_DATE)
d3$END_DATE <- NULL

d3$yr <- as.numeric(format(d3$date, "%Y"))

d3$Month <- as.numeric(format(d3$date, "%m"))

#Holiday

# Independence Day
d3$july4 <- ifelse(format(d3$date, "%m-%d") == "07-04",1,0)

# Juneteenth
d3$juneteenth <- ifelse(format(d3$date, "%m-%d") == "06-19",1,0)

# Mother's Day
mother <- as.Date(sapply(d3$yr, function(y) {
  x <- as.Date(paste0(y, "-05-01"))
  x + (8 - as.POSIXlt(x)$wday) %% 7 + 6
}))
d3$mother <- ifelse(d3$date == mother,1,0)

# Father's Day
father <- as.Date(sapply(d3$yr, function(y) {
  x <- as.Date(paste0(y, "-06-01"))
  x + (8 - as.POSIXlt(x)$wday) %% 7 + 13
}))
d3$father <- ifelse(d3$date == father,1,0)

# Memorial Day
memorial <- as.Date(sapply(d3$yr, function(y) {
  x <- as.Date(paste0(y, "-05-01"))
  x - as.POSIXlt(x)$wday %% 7 + 29
}))
d3$memorial <- ifelse(d3$date == memorial,1,0)

# Labor Day
labor <- as.Date(sapply(d3$yr, function(y) {
  x <- as.Date(paste0(y, "-09-01"))
  x + (8 - as.POSIXlt(x)$wday) %% 7
}))
d3$labor <- ifelse(d3$date == labor,1,0)

# single holiday
d3$holiday <- as.integer(d3$july4 | d3$memorial | d3$labor | d3$juneteenth | d3$mother | d3$father)


#quasi pois model for 2026
quasi_pois_model_all3 <- glm(
  HEAT_ED_VISIT_COUNT ~ MAX_DAILY_TEMP + Month + holiday,
  family = quasipoisson(link = "log"),
  data = d3
)

summary(quasi_pois_model_all3)

#year is constant

```

## Prediction

```{r}
d$yr <- as.numeric(as.character(d$yr))
d$Month <- as.numeric(as.character(d$Month))

quasi_pois_model_all <- glm(
  HEAT_ED_VISIT_COUNT ~ MAX_DAILY_TEMP + holiday + yr + Month,
  family = quasipoisson(link = "log"),
  data = d )

pred_20261 <- predict(
  quasi_pois_model_all,
  newdata = d3,
  type = "response"
)

d3$Ph1<- pred_20261

plot(
  d3$date,
  d3$HEAT_ED_VISIT_COUNT,
  pch = 16,
  xlab = "Date (2026)",
  ylab = "Heat-Related ED Visits",
  main = "Observed vs Predicted Heat ED Visits: 2026"
)

lines(
  d3$date,
  d3$Ph1,
  col = "red",
  lwd = 2
)

legend(
  "topleft",
  legend = c("Observed", "Predicted"),
  pch = c(16, NA),
  lty = c(NA, 1),
  col = c("black", "red")
)
```

Prediction With Lags

```{r}

temp_by_year3 <- split(d3$MAX_DAILY_TEMP, d3$yr)

for (i in 0:6) {
  d3[[paste0("lag", i)]] <- unlist(
    lapply(temp_by_year3, function(x) {
      if (i == 0) {
        x
      } else {
        c(rep(NA, i), head(x, -i))
      }
    }),
    use.names = FALSE
  )
}

head(d3[, c("date", "MAX_DAILY_TEMP",
           "lag1",
           "lag6")])

quasi_pois_model_all_2 <- glm(
  HEAT_ED_VISIT_COUNT ~ MAX_DAILY_TEMP + holiday + yr + Month + lag1 + lag2 + lag3 + lag4 + lag5 + lag6,
  family = quasipoisson(link = "log"),
  data = d )

pred_20262 <- predict(
  quasi_pois_model_all,
  newdata = d3,
  type = "response"
)

d3$Ph2 <- pred_20262

plot(
  d3$date,
  d3$HEAT_ED_VISIT_COUNT,
  pch = 16,
  xlab = "Date (2026)",
  ylab = "Heat-Related ED Visits",
  main = "Observed vs Predicted Heat ED Visits: 2026"
)

lines(
  d3$date,
  d3$Ph2,
  col = "red",
  lwd = 2
)

legend(
  "topleft",
  legend = c("Observed", "Predicted"),
  pch = c(16, NA),
  lty = c(NA, 1),
  col = c("black", "red")
)

```

RMSE

```{r}

rmse_base <- sqrt(mean((d3$HEAT_ED_VISIT_COUNT-d3$Ph2)^2, na.rm = TRUE))
print(rmse_base)

rmse_base1 <- sqrt(mean((d3$HEAT_ED_VISIT_COUNT-d3$Ph1)^2, na.rm = TRUE))
print(rmse_base1)

```
